---
permalink: deploy/reference-key-points-about-assigning-and-modifying-permissions.html 
sidebar: sidebar 
keywords: key, points, about, assigning, modifying, permissions, vcenter, server, 
summary: 使用vCenter Server權限時、請謹記幾個重點。VMware vSphere的虛擬儲存主控台工作是否成功、取決於您指派權限的位置、或使用者在修改權限後採取的動作。 
---
= 指派和修改vCenter Server權限的重點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用vCenter Server權限時、請謹記幾個重點。VMware vSphere的虛擬儲存主控台工作是否成功、取決於您指派權限的位置、或使用者在修改權限後採取的動作。



== 指派權限

如果您只想限制對vSphere物件和工作的存取、則只需要設定vCenter Server權限。否則、您可以以系統管理員的身分登入。此登入可讓您自動存取所有vSphere物件。

指派權限的位置決定使用者可以執行的VSC工作。

有時候、為了確保工作完成、您必須在較高層級（例如根物件）指派權限。當工作需要不適用於特定vSphere物件的權限（例如追蹤工作）、或是需要的權限套用至非vSphere物件（例如儲存系統）時、就會發生這種情況。

在這些情況下、您可以設定權限、讓子實體繼承權限。您也可以將其他權限指派給子實體。指派給子實體的權限一律會覆寫繼承自父實體的權限。這表示您可以將權限授予子實體、以限制指派給根物件並由子實體繼承的權限範圍。


TIP: 除非貴公司的安全性原則需要更嚴格的權限、否則指派權限給根物件（也稱為根資料夾）是很好的做法。



== 權限與非vSphere物件

您建立的權限會套用至非vSphere物件。例如、儲存系統不是vSphere物件。如果某項權限適用於儲存系統、您必須將包含該權限的權限指派給VSC根物件、因為您無法將該權限指派給vSphere物件。

例如、任何包含VSC權限的權限、例如「新增/修改/跳過儲存系統」、都必須在根物件層級指派。



== 修改權限

您可以隨時修改一個權限。

如果您變更權限內的權限、則與該權限相關的使用者應登出、然後重新登入以啟用更新的權限。
