---
permalink: deploy/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, storage, systems, 
summary: 您可以使用VMware vSphere的虛擬儲存主控台、為vCenter Server中的儲存系統設定預設認證。 
---
= 設定儲存系統的預設認證資料
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用VMware vSphere的虛擬儲存主控台、為vCenter Server中的儲存系統設定預設認證。

您必須選取要用來建立預設認證的vCenter Server。

如果您為儲存系統設定預設認證、（VSC）會使用這些認證資料來登入VSC剛發現的儲存系統。如果預設認證無法運作、您必須手動登入儲存系統。VSC和SRA支援在叢集層級或層級新增儲存系統認證。但是VASA Provider只能使用叢集層級認證。

.步驟
. 在VSC * Home*頁面上、按一下功能表：設定[系統管理設定>設定儲存系統的預設認證]。
. 在*儲存系統預設認證*對話方塊中、輸入儲存系統的使用者名稱和密碼。
+
儲存控制器認證資料會根據ONTAP 使用者名稱和密碼配對、以位在畫面中指派。儲存控制器認證可以是系統管理員帳戶、也可以是使用角色型存取控制（RBAC）的自訂帳戶。

+
您無法使用VSC來變更與儲存控制器的使用者名稱和密碼配對相關的角色。若要修改或建立用於ONTAP VSC、VASA Provider和SRA的虛擬應用裝置的新版「功能不全」使用者角色、您可以使用System Manager。

+
請參閱_Virtual Storage Console、VASA Provider和Storage Replication Adapter for VMware®vSphere Deployment and Setup Guide for 9.7版本_中的「設定使用者角色與權限」一節。

. 按一下「*確定*」以儲存預設認證。


如果您因為儲存系統回報「驗證失敗」狀態而更新儲存系統認證、您應該按一下「儲存系統」頁面上的「*重新探索全部*」選項。執行此動作時、VSC會嘗試使用新認證來連線至儲存系統。
