---
permalink: manage/concept-what-storage-capabilities-are.html 
sidebar: sidebar 
keywords: storage, capability, profiles, 
summary: 儲存功能是一組儲存系統屬性、可識別特定層級的儲存效能、儲存效率及其他功能、例如與儲存功能相關的儲存物件加密。 
---
= 什麼是儲存功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存功能是一組儲存系統屬性、可識別特定層級的儲存效能、儲存效率及其他功能、例如與儲存功能相關的儲存物件加密。

對於傳統的資料存放區、您可以使用儲存功能設定檔、以一致的方式建立具有通用屬性的資料存放區、並將QoS原則指派給這些資料存放區。在資源配置期間、VSC會顯示符合儲存功能設定檔的叢集、SVM和集合體。您可以使用「*儲存對應*」功能表中的「*全域自動產生設定檔*」選項、從現有的傳統資料存放區產生儲存功能設定檔。建立設定檔之後、您可以使用VSC來監控資料存放區與設定檔的相容性。

與VVOL資料存放區搭配使用時、資源配置精靈可以使用多個儲存功能設定檔、在FlexVol 資料存放區中建立不同的支援區。您可以使用VM儲存原則、自動建立虛擬機器的VVols、使其符合FlexVol 所定義的適當功能。例如、您可以為一般儲存類別建立設定檔（例如效能限制和其他功能、例如加密或FabricPool VMware等）。您可以稍後在vCenter Server中建立VM儲存原則、以代表虛擬機器的商業類別、並依名稱將這些原則連結至適當的儲存功能設定檔（例如：正式作業、測試、人力資源）。

搭配VVols使用時、儲存功能設定檔也可用來設定個別虛擬機器的儲存效能、並將其放在FlexVol VVol資料存放區的VMware Volume上、以最符合效能需求。您可以針對效能指定最低和/或最高IOPS的QoS原則。您可以在最初配置虛擬機器時使用預設原則、或是在業務需求變更時稍後變更VM儲存原則。

然後vCenter Server會將LUN或磁碟區的儲存功能與該LUN或磁碟區上的資源存放區建立關聯。這可讓您在符合虛擬機器儲存設定檔的資料存放區中配置虛擬機器、並確保資料存放區叢集中的所有資料存放區都具有相同的儲存服務層級。

有了適用於虛擬儲存主控台（VSC）、VASA Provider及儲存複寫介面卡（SRA）的虛擬應用裝置、您就能使用新的儲存功能設定檔來設定每個虛擬Volume（VVOL）資料存放區、以支援在同一個VVol資料存放區上配置具有不同IOPS需求的虛擬機器。在執行具有IOPS需求的VM資源配置工作流程時、所有VVOL資料存放區都會列在相容的資料存放區清單中。

[NOTE]
====
當您嘗試為6.5之前的vCenter Server配置或修改虛擬機器時、相容的資料存放區清單中只會列出包含效能設定為「MAX IOPS」之儲存功能設定檔的VVol資料存放區。其餘vVol資料存放區會列在不相容的資料存放區清單中。您可以忽略此分類、並從不相容的資料存放區清單中選取任何vVol資料存放區、以進行資源配置或修改虛擬機器。

====