---
permalink: manage/concept-datastore-reports.html 
sidebar: sidebar 
keywords: datastore, reports, 
summary: 資料存放區報告提供有關傳統資料存放區和在這些資料存放區上建立之虛擬機器的詳細資訊。 
---
= 資料存放區報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資料存放區報告提供有關傳統資料存放區和在這些資料存放區上建立之虛擬機器的詳細資訊。

傳統儀表板可讓您檢閱及識別vCenter Server中資料存放區和虛擬機器的潛在問題。您可以檢視、排序及匯出報告。傳統資料存放區和虛擬機器的資料報告由vCenter Server提供。

資料存放區提供下列預先定義的報告：

* 資料存放區報告
* 虛擬機器報告




== 資料存放區報告

資料存放區報告功能表提供下列資料存放區參數的相關資訊：

* 資料存放區名稱
* 資料存放區類型：NFS或VMFS
* 可用空間
* 已用空間
* 總空間
* 使用空間百分比
* 可用空間百分比
* IOPS
+
報告會顯示資料存放區的IOPS。

* 延遲
+
報告會顯示資料存放區的延遲資訊。



您也可以確認產生報告的時間。資料存放區報告功能表可讓您根據需求來組織報告、然後使用*匯出至CSV*按鈕匯出組織報告。報告中的資料存放區名稱是導覽至所選資料存放區之「監控」索引標籤的連結、您可在其中檢視資料存放區效能指標。



== 虛擬機器報告

「虛擬機器報告」功能表針對使用VSC針對所選vCenter Server所配置之資料存放區的所有虛擬機器、提供下列效能指標：

* 虛擬機器名稱
* 承諾容量
+
報告會顯示虛擬機器已提交容量的值。

* 正常運作時間
+
報告會顯示虛擬機器已開機且可在ESXi主機上使用的時間。

* 延遲
+
報告會顯示虛擬機器在所有與虛擬機器相關聯的資料存放區之間的延遲時間。

* 電源狀態
+
報告會顯示虛擬機器是開啟還是關閉。

* 主機
+
報告會顯示可供虛擬機器使用的主機系統。



報告中的每個虛擬機器名稱都是指向所選虛擬機器之「監控」索引標籤的連結。您可以根據需求來排序虛擬機器報告、並將報告匯出至「.CSV」檔案、然後將報告儲存在本機系統上。報告的時間戳記也會附加至儲存的報告。
