---
permalink: manage/task-map-storage-to-storage-capability-profiles.html 
sidebar: sidebar 
keywords: mapping, datastores, to, storage, capability, profiles, 
summary: 您可以將與VASA Provider相關聯的資料存放區對應ONTAP 至儲存功能設定檔。您可以將設定檔指派給與儲存功能設定檔無關的資料存放區。 
---
= 將資料存放區對應至儲存功能設定檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將與VASA Provider相關聯的資料存放區對應ONTAP 至儲存功能設定檔。您可以將設定檔指派給與儲存功能設定檔無關的資料存放區。

.開始之前
* 您必須已在VMware vSphere的虛擬儲存主控台註冊VASA Provider執行個體。
* 虛擬儲存主控台（VSC）必須已探索到您的儲存設備。


您可以使用儲存功能設定檔來對應傳統資料存放區、或變更與資料存放區相關聯的儲存功能設定檔。VASA Provider不會在「*儲存對應*」頁面上顯示任何虛擬Volume（VVOL）資料存放區。此工作中提及的所有資料存放區都是傳統的資料存放區。

.步驟
. 在VSC *主頁*頁面中、按一下*儲存對應*。
+
從*儲存對應*頁面、您可以判斷下列資訊：

+
** 與資料存放區相關聯的vCenter Server
** 有多少設定檔符合資料存放區
+
「*儲存對應*」頁面僅顯示傳統的資料存放區。此頁面不會顯示任何VVOL資料存放區或qtree資料存放區。

** 資料存放區目前是否與設定檔相關聯
+
資料存放區可以比對多個設定檔、但資料存放區只能與一個設定檔建立關聯。

** 資料存放區是否符合與其相關聯的設定檔


. 若要將儲存功能設定檔對應至資料存放區、或變更資料存放區的現有設定檔、請選取資料存放區。
+
若要在「*儲存對應*」頁面上找到特定的資料存放區或其他資訊、您可以在搜尋方塊中輸入名稱或部分字串。VSC會在對話方塊中顯示搜尋結果。若要返回完整顯示畫面、您應該從搜尋方塊中移除文字、然後按一下* Enter *。

. 從「*動作*」功能表中、選取*指派相符的設定檔*。
. 從「*指派設定檔至資料存放區*」對話方塊中提供的相符設定檔清單中、選取您要對應至資料存放區的設定檔、然後按一下「*確定*」、將選取的設定檔對應至資料存放區。
. 重新整理畫面以驗證新指派。

