---
permalink: manage/task-provision-datastores.html 
sidebar: sidebar 
keywords: provisioning, datastores, 
summary: 資源配置資料存放區會為虛擬機器及其虛擬機器磁碟（VMDK）建立邏輯容器。您可以配置資料存放區、然後將資料存放區附加至單一主機、叢集中的所有主機、或資料中心內的所有主機。 
---
= 配置資料存放區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資源配置資料存放區會為虛擬機器及其虛擬機器磁碟（VMDK）建立邏輯容器。您可以配置資料存放區、然後將資料存放區附加至單一主機、叢集中的所有主機、或資料中心內的所有主機。

.開始之前
* 若要在直接連線至虛擬儲存主控台（VSC）的SVM上配置資料存放區、您必須使用具有適當權限的使用者帳戶、而非預設vsadmin使用者帳戶或vsadmin角色、將SVM新增至VSC。
+
您也可以新增叢集來配置資料存放區。

* 您必須確保ESXi所裝載之所有網路的子網路詳細資料都輸入到「kaminoprefs.xml」中。
+
請參閱_VSC 9.6部署與設定指南_中的「啟用跨不同子網路的資料存放區裝載」一節。

* 如果您使用NFS或iSCSI、且ESXi主機與儲存系統之間的子網路不同、則「kaminoprefs」偏好設定檔中的NFS或iSCSI設定必須包含ESXi主機子網路遮罩。
+
此偏好設定檔也適用於VVOL資料存放區建立。_9.6版的虛擬儲存主控台、VASA供應商及儲存複寫介面卡部署與設定指南（_Virtual Storage Console、VASA Provider and Storage Replication Adapter Deployment and Setup Guide for 9.6）提供更多關於喜好設定檔案的資訊、以及在不同子網路之間啟用資料存放區

* 如果您已啟用VASA Provider並想要指定NFS資料存放區或VMFS資料存放區的儲存功能設定檔、則必須建立一個或多個儲存功能設定檔。
* 若要建立NFSv4.1資料存放區、您必須在SVM層級啟用NFSv4.1。


.關於這項工作
「*資源配置資料庫*」選項可讓您指定資料存放區的儲存功能設定檔。儲存功能設定檔有助於指定一致的服務層級目標（SLO）、並簡化資源配置程序。只有啟用VASA Provider、才能指定儲存功能設定檔。VSC、VASA Provider和SRA的虛擬應用裝置支援下列傳輸協定：

* NFSv3和NFSv4.1
* VMFS5和VMFS6


VSC可以在NFS磁碟區或LUN上建立資料存放區：

* 對於NFS資料存放區、VSC會在儲存系統上建立NFS磁碟區、然後更新匯出原則。
* 對於VMFS資料存放區、VSC會建立新的磁碟區（如果您選取該選項、則會使用現有的磁碟區）、然後建立LUN和igroup。


[NOTE]
====
VMware不支援使用資料存放區叢集的NFSv4.1。

====
如果資源配置期間未指定儲存功能設定檔、您可以稍後使用「儲存對應」頁面、將資料存放區對應至儲存功能設定檔。

.步驟
. 您可以使用下列其中一項來存取資料存放區資源配置精靈：
+
[cols="1a,1a"]
|===
| 如果您選擇... | 執行下列動作... 


 a| 
* vSphere用戶端首頁*
 a| 
.. 按一下*主機與叢集*。
.. 在導覽窗格中、選取您要在其中配置資料存放區的資料中心。
.. 若要指定要掛載資料存放區的主機、請參閱下一步。




 a| 
*虛擬儲存主控台首頁*
 a| 
.. 按一下「*總覽*」。
.. 按一下*入門*索引標籤。
.. 按一下「*資源配置*」按鈕。
.. 按一下「*瀏覽*」、選取下一步要佈建資料存放區的目的地。


|===
. 指定要掛載資料存放區的主機。
+
[cols="1a,1a"]
|===
| 若要讓資料存放區可供... | 執行此動作... 


 a| 
資料中心內的所有主機
 a| 
以滑鼠右鍵按一下資料中心、然後選取功能表：NetApp VSC[資源存放區資源配置]。



 a| 
叢集中的所有主機
 a| 
以滑鼠右鍵按一下主機叢集、然後選取功能表：NetApp VSC[資源存放區資源配置]。



 a| 
單一主機
 a| 
以滑鼠右鍵按一下主機、然後選取功能表：NetApp VSC[資源存放區資源配置]。

|===
. 填寫「*新資料存放區*」對話方塊中的欄位、以建立資料存放區。
+
對話方塊中的大部分欄位都是不言自明的。下表說明您可能需要指引的部分欄位。

+
[cols="1a,1a"]
|===
| 區段 | 說明 


 a| 
一般
 a| 
「*新資料存放區資源配置*」對話方塊的「*一般*」區段提供選項、可輸入新資料存放區的目的地、名稱、大小、類型和傳輸協定。您可以選取* NFS*或* VMFS*傳輸協定來設定傳統的資料存放區。VVOL資料存放區類型是用來設定VVOL資料存放區。如果已啟用VASA Provider、您也可以決定是否使用儲存功能設定檔。*資料存放區叢集*選項僅適用於傳統資料存放區。您應該使用*進階*選項來指定* VMFS5*或* VMFS6*檔案系統。



 a| 
儲存系統
 a| 
如果您已在*一般*區段中選取選項、則可以選取列出的其中一個儲存功能設定檔。儲存系統和儲存虛擬機器的系統建議值會填入以供輕鬆使用。但您可以視需要修改這些值。



 a| 
儲存屬性
 a| 
根據預設、VSC會填入* Aggregate *和* Volumes *選項的建議值。您可以根據需求自訂值。「*進階*」功能表下的*空間保留*選項也會填入以提供最佳結果。



 a| 
摘要
 a| 
您可以檢閱您為新資料存放區指定的參數摘要。

|===
. 在「*摘要*」區段中、按一下「*完成*」。

