---
permalink: manage/task-monitor-vvols-datastores-and-virtual-machines-using-vvols-dashboard.html 
sidebar: sidebar 
keywords: monitoring, vvols, datastores, virtual, machines, using, the, vVol, dashboard, 
summary: 您可以監控效能、並根據您使用虛擬儲存主控台（VSC）、VASA供應商及儲存複寫介面卡（SRA）虛擬應用裝置的vVol儀表板所選取的參數、檢視vCenter Server中前五大SAN VMware虛擬磁碟區（vVols）資料存放區。 
---
= 使用vVol儀表板監控vVols資料存放區和虛擬機器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以監控效能、並根據您使用虛擬儲存主控台（VSC）、VASA供應商及儲存複寫介面卡（SRA）虛擬應用裝置的vVol儀表板所選取的參數、檢視vCenter Server中前五大SAN VMware虛擬磁碟區（vVols）資料存放區。

.開始之前
* 如果您使用的是版本為6、9.6或更早版本、則應該啟用OnCommand 了「支援不支援的API Services 2.1」或更新版本ONTAP 。
+
您不需要向OnCommand VASA Provider登錄《EFlash API服務》、即可取得SAN vVols資料存放區或SAN vVols VM資料存放區報告ONTAP 的詳細資料、以利執行更新。

+
https://mysupport.netapp.com/site/["NetApp支援"^]

* 您應該使用ONTAP 適用於儲存系統的不含更新版本的功能。


link:reference-verify-vvol-dashboard-data-requirements.html["VVOL儀表板資料需求"]

由NetApp提供的IOPS資料ONTAP 會四捨五入、並顯示在VVol儀表板上。可能是ONTAP 因為由供應的實際IOPS值與VVol儀表板上顯示的IOPS值有所不同。

[NOTE]
====
* 如果OnCommand 您是第一次登錄「VMware API服務」、那麼您只能在15到30分鐘後、檢視VVol儀表板上SAN vVols資料存放區的所有效能指標資料。
* vVol儀表板資料會定期重新整理、時間間隔為10分鐘。
* 如果您已從vCenter Server執行個體新增、修改或刪除儲存系統、則vVols儀表板上的資料可能會有一段時間沒有任何變更。
+
這是因為OnCommand 無法從ONTAP 更新的指標上取得更新的資料、而需要花費一些時間。

* VVol儀表板*總IOPS值顯示在「VVol」（虛擬磁碟區）的「Overview」（概觀）入口小程序中、並非「讀取IOPS」值和「寫入IOPS」值的累計值。
+
讀取IOPS、寫入IOPS和總IOPS是OnCommand 由NetApp API Services提供的獨立數據。如果OnCommand 整體IOPS值與由現象API服務提供的累積IOPS值（讀取IOPS值+寫入IOPS值）有差異、則VVol儀表板上的IOPS值會出現相同差異。



====
.步驟
. 在vSphere Client主頁中、按一下*虛擬儲存主控台*。
. 使用* vCenter server*下拉式功能表選取所需的vCenter Server、以檢視資料存放區。
. 按一下* vVol Dashboard *。
+
*資料存放區*入口小程序提供下列詳細資料：

+
** vCenter Server執行個體中由VASA Provider管理的vVols資料存放區數目
** 前五大vVols資料存放區是根據資源使用量和效能參數、您可以根據所用空間、IOPS或延遲、以及所需的順序來變更資料存放區清單。


. 使用*虛擬機器*入口小工具檢視虛擬機器的詳細資料。
+
*虛擬機器*入口小程序提供下列詳細資料：

+
** 使用vCenter Server中的資料存放區的虛擬機器數量ONTAP
** 前五大虛擬機器、以IOPS、延遲、處理量、承諾容量、正常運作時間、 以及邏輯空間、您可以自訂在VVol儀表板中列出前五大虛擬機器的方式。



